name: balance_swiper
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 1.0.0
author: Minsu Lee <minsu.lee@dietfriends.kr>
homepage: https://github.com/dietfriends/balance_swiper

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=0.1.4 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: '^1.11.0'

flutter:
