name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  packages:
    name: ${{ matrix.version }}-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 2.0.0
          - version: 2.2.0
    #container:
    #  image: cirrusci/flutter:${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-install-cache-${{ matrix.version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.version }}
      - name: Install dependencies
        run: |
          flutter pub get

      - name: Run tests
        run: |
          flutter test --coverage test

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        if: ${{ matrix.version == '2.2.0' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: app
          file: ./coverage/lcov.info
